version: '2'

services:

  moodle_db:
    image: postgres
    volumes:
      - './data/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: $MOODLE_DB_NAME
      POSTGRES_USER: $MOODLE_DB_USER
      POSTGRES_PASSWORD: $MOODLE_DB_PASSWORD

  moodle:
    image: ellakcy/moodle:latest
    volumes:
      - './data/moodle:/var/moodledata'
    ports:
      - '8082:80'
    links:
      - moodle_db
    environment:
      MOODLE_URL: $MOODLE_URL
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_TYPE: "mariadb"
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
