version: '2'

networks:
  app-tier:
    driver: bridge

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'nginx'
    restart: always
    environment:
      DOMAINS: '${MOODLE_DOMAIN} -> http://moodle:8082'
      STAGE: '${MOODLE_DOMAIN_STAGE}'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
    networks:
      - app-tier

  moodle_db:
    image: mariadb:10.2
    ports:
      - '3306:3306'
    volumes:
      - '${MOODLE_DATAROOT}/mariadb_data:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ONETIME_PASSWORD: 'yes'
      MYSQL_DATABASE: '${MOODLE_DB_NAME}'
      MYSQL_USER: '${MOODLE_DB_USER}'
      MYSQL_PASSWORD: '${MOODLE_DB_PASSWORD}'
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - '${MOODLE_DATAROOT}/redis_data:/bitnami'
    networks:
      - app-tier

  moodle:
    image: artnight/moodle:mysql_maria_apache
    volumes:
      - '${MOODLE_DATAROOT}/moodle_data:/var/moodledata'
      - '${MOODLE_DATAROOT}/moodle_html:/var/www/html'
    ports:
      - '8082:80'
    links:
      - 'moodle_db'
      - 'redis'
    environment:
      MOODLE_URL: $MOODLE_URL
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_TYPE: 'mariadb'
      MOODLE_DB_HOST: 'moodle_db'
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: $MOODLE_REVERSE_LB
      MOODLE_SSL: $MOODLE_SSL
      MOODLE_EMAIL_TYPE_QMAIL: $MOODLE_EMAIL_TYPE_QMAIL
      MOODLE_EMAIL_HOST: $MOODLE_EMAIL_HOST
      MOODLE_REDIS_HOST: $MOODLE_REDIS_HOST
      MOODLE_REDIS_PORT: $MOODLE_REDIS_PORT
    networks:
      - app-tier
